language : crystal
addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.6
      - ubuntu-toolchain-r-test
    packages:
      - llvm-3.6-dev
      - libllvm3.6
      - llvm-3.6
      - llvm-3.6-runtime
      - libstdc++6

script:
  - g++ -o /opt/crystal/src/llvm/ext/llvm_ext.o -c /opt/crystal/src/llvm/ext/llvm_ext.cc $(llvm-config-3.6 --cxxflags)
  - crystal spec -s
